import { Link } from "wouter";
import { Atom, ArrowLeft } from "lucide-react";

export function Terms() {
  return (
    <div className="min-h-screen bg-[hsl(224_71%_4%)] text-[hsl(213_31%_91%)]">
      <nav className="border-b border-[hsl(216_34%_17%)]">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center gap-3">
          <Link
            href="/"
            className="flex items-center gap-2 text-xs text-[hsl(215.4_16.3%_56.9%)] hover:text-[hsl(213_31%_91%)] transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            Back
          </Link>
          <div className="ml-auto flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-[hsl(210_100%_66%/0.15)] flex items-center justify-center">
              <Atom className="w-4 h-4 text-[hsl(210_100%_66%)]" />
            </div>
            <span className="font-bold text-sm">FirstPrinciples Explorer</span>
          </div>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-4 py-14 space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
          <p className="text-sm text-[hsl(215.4_16.3%_56.9%)] mt-2">
            Last updated: May 13, 2025
          </p>
        </div>

        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using FirstPrinciples Explorer ("the Service"), you agree to be bound
            by these Terms of Service. If you do not agree to these terms, please do not use the
            Service.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            FirstPrinciples Explorer is an AI-powered tool that generates hierarchical breakdowns
            of topics from first principles, interactive flowcharts, innovation gap analysis, and
            AI-generated visuals using the xAI Grok API. The Service is offered on a free tier
            (bring-your-own API key) and a paid Pro tier.
          </p>
        </Section>

        <Section title="3. Accounts and Registration">
          <p>
            You must create an account to access paid features. You are responsible for maintaining
            the confidentiality of your account credentials and for all activity that occurs under
            your account. You must provide accurate and complete information when registering.
          </p>
        </Section>

        <Section title="4. Payments and Subscriptions">
          <ul>
            <li>
              Pro subscriptions are billed monthly ($12/month) or annually ($108/year) via Stripe.
            </li>
            <li>
              Topic Credits are one-time purchases that never expire.
            </li>
            <li>
              Subscriptions renew automatically at the end of each billing period. You may cancel
              at any time through the billing portal — cancellation takes effect at the end of the
              current period.
            </li>
            <li>
              All charges are in US dollars. We do not offer refunds for partial subscription
              periods or unused topic credits except where required by law.
            </li>
            <li>
              If your payment fails, your Pro access will be revoked until payment is resolved.
            </li>
          </ul>
        </Section>

        <Section title="5. Acceptable Use">
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any unlawful purpose or in violation of any regulations.</li>
            <li>
              Attempt to circumvent rate limits, quotas, or access controls through automated
              tools, scripts, or other means.
            </li>
            <li>
              Resell, sublicense, or redistribute access to the Service without our express written
              permission.
            </li>
            <li>
              Use the Service to generate content that is harmful, deceptive, or violates the
              rights of others.
            </li>
            <li>
              Reverse engineer or attempt to extract the underlying AI models or server-side API
              keys.
            </li>
          </ul>
        </Section>

        <Section title="6. AI-Generated Content">
          <p>
            The Service generates content using large language models (xAI Grok). AI-generated
            content may be inaccurate, incomplete, or outdated. You should independently verify
            any information before relying on it for important decisions.
          </p>
          <p className="mt-3">
            <strong>Financial Disclaimer:</strong> Innovation gap analysis and stock information
            generated by the Service is for informational and educational purposes only. It does
            not constitute financial, investment, or trading advice. Always consult a qualified
            financial advisor before making investment decisions.
          </p>
        </Section>

        <Section title="7. Intellectual Property">
          <p>
            The Service, including its design, code, and branding, is owned by FirstPrinciples
            Explorer and protected by applicable intellectual property laws. Content you generate
            using the Service belongs to you, subject to any restrictions imposed by the underlying
            AI providers.
          </p>
        </Section>

        <Section title="8. Disclaimers and Limitation of Liability">
          <p>
            The Service is provided "as is" without warranties of any kind, express or implied. We
            do not warrant that the Service will be uninterrupted, error-free, or that AI-generated
            content will be accurate.
          </p>
          <p className="mt-3">
            To the fullest extent permitted by law, we shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages arising from your use of the
            Service, even if we have been advised of the possibility of such damages.
          </p>
        </Section>

        <Section title="9. Changes to Terms">
          <p>
            We may update these Terms from time to time. We will notify users of material changes
            by updating the "Last updated" date above. Continued use of the Service after changes
            are posted constitutes your acceptance of the revised Terms.
          </p>
        </Section>

        <Section title="10. Governing Law">
          <p>
            These Terms are governed by and construed in accordance with applicable law. Any
            disputes shall be resolved through binding arbitration or in the courts of competent
            jurisdiction.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            If you have questions about these Terms, please reach out via the contact information
            on our site.
          </p>
        </Section>

        <div className="pt-4 border-t border-[hsl(216_34%_17%)] text-xs text-[hsl(215.4_16.3%_46.9%)] flex gap-4">
          <Link href="/privacy" className="hover:text-[hsl(213_31%_71%)] transition-colors">
            Privacy Policy
          </Link>
          <Link href="/" className="hover:text-[hsl(213_31%_71%)] transition-colors">
            Home
          </Link>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-semibold text-[hsl(213_31%_91%)]">{title}</h2>
      <div className="text-sm text-[hsl(215.4_16.3%_76.9%)] leading-relaxed space-y-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-2">
        {children}
      </div>
    </section>
  );
}
